### ISSUE TITLE
Question Regarding Zero-Shot Evaluation

### ISSUE THREAD

**Issue by chris-jaehoon** [Junyi42/GeoAware-SC#14]
After cloning the repository and running process_map.py, I performed a zero-shot evaluation on Spair-71K. 
If there’s a performance discrepancy compared to the results reported in the paper, what could be the possible reasons?

**Comment by Junyi42** [comment]
Hi @chris-jaehoon,

Thanks for the feedback. I saw your email regarding the results "align more closely with the zero-shot performance mentioned in the abstract, not the Table 2". I believe this is because the difference in evaluation protocol (per point vs. per image). The same issue is explained here: https://github.com/Junyi42/GeoAware-SC/issues/4#issuecomment-2106236069

Thanks!

**Comment by chris-jaehoon** [comment]
it is solved. Thank you!
