### ISSUE TITLE
Recreating results exactly

### ISSUE THREAD

**Issue by ehedlin** [Junyi42/GeoAware-SC#4]
For preprocessing SD+DINO did you use a specific seed? I am trying to recreate the results exactly but I am getting some results that are better and some that are worse than whats listed in your paper. 

If not do you still happen to have the data used after the preprocessing? It would be much appreciated. I recognize its a large amount of data so if you do I can look into ways of transferring the files  :)

**Comment by ehedlin** [comment]
I realized I modified something before precomputing and that there is a seed, all good :)

**Comment by ehedlin** [comment]
I re installed the repository and re-precomputed and am getting similar results. 76.42% instead of 78.0% for airplane for example

**Comment by ehedlin** [comment]
![Screen Shot 2024-05-11 at 7 51 49 PM](https://github.com/Junyi42/GeoAware-SC/assets/23744775/4471e8a2-6de4-48e0-a13d-ff76b57d77af)
Top row is results I got and bottom is results listed in paper

**Comment by Junyi42** [comment]
> ![Screen Shot 2024-05-11 at 7 51 49 PM](https://private-user-images.githubusercontent.com/23744775/329822682-4471e8a2-6de4-48e0-a13d-ff76b57d77af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTc2MTIsIm5iZiI6MTcxNTUxNzMxMiwicGF0aCI6Ii8yMzc0NDc3NS8zMjk4MjI2ODItNDQ3MWU4YTItNmRlNC00OGUwLWExM2QtZmY3NmI1N2Q3N2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODM3NWZiOTZiOWM1ZTcxOGM3ZjI1ODRlNWQwNzUwYjMzZTA2NmVlYjljMTA0ZTQ5YTk5ZjAyYmQ3YTllMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MsRWb-rKSLbS1lPRcldfDJN5OKXxJpzUFf6NzcI-c4w) Top row is results I got running the repo code and bottom is results listed in paper

Hi @ehedlin,

Thanks so much for your feedback! 

I assume you were running the command `python pck_train.py --config configs/train_ap10k.yaml`. If so, the reason for the difference is due to the evaluation setting. As stated in the caption of Tab. 2, the reported result for the unsupervised method (i.e., the bottom row of your posted table) is under a **per keypoint** evaluation setting, while the default setup in `configs/train_ap10k.yaml` (also, the top row of your posted table) in under the **per image** setting. More details below, and you could also refer to the DIFT paper for the difference of two settings.
![image](https://github.com/Junyi42/GeoAware-SC/assets/90844802/eceeab1c-3301-4462-843a-9e77a83ebdbb)

To get the result under the **per keypoint** setting, you could simply run `python pck_train.py --config configs/train_ap10k.yaml --KPT_RESULT`. By the way, it is often the case that **per image** number is lower than the **per keypoint** setting. 

I will update more details in the instructions, and please feel free to let me know if it works, thanks!

**Comment by ehedlin** [comment]
Ah, that makes sense. Thank you for pointing that out :)
